name: Require Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  require-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for required labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 2
          labels: |
            feature
            bug
            documentation
            tech-debt
          add_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check for priority label
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: |
            priority: high
            priority: medium
            priority: low
          add_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
